import { StyleSheet } from "react-native";

export const Colors = {
  textBorder: "#222222",
  buttonRed: "#580C1F",
  buttonGreen: "#69A75F",
  background: "#D9D9D9",
  white: "#ffffff",
  lightGrey: "#D9D9D9",
  mediumGrey: "#d9d9d9",
  darkGrey: "#555",
  tableBorder: "#aaa",
  tableRowBorder: "#eee",
  pendingStatus: "#E7D54C",
  deniedStatus: "#C75B5C",
  approvedStatus: "#69A75F",
  black: "#000000",
  buttonPrimary: "#69A75F",
};

const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.lightGrey,
  },
  mainContent: {
    flex: 1,
    overflow: "hidden",
  },
  scrollViewContent: {
    padding: 20,
    paddingBottom: 80,
  },
  sectionContainer: {
    backgroundColor: "transparent",
    borderRadius: 8,
    padding: 0,
    marginBottom: 20,
    overflow: "hidden",
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: Colors.black,
    marginBottom: 20,
  },
  table: {
    width: "100%",
    alignSelf: "center",
    borderWidth: 2,
    borderColor: Colors.tableBorder,
    borderRadius: 4,
    overflow: "hidden",
    backgroundColor: Colors.background,
  },
  headerRow: {
    flexDirection: "row",
    backgroundColor: Colors.background,
    paddingVertical: 8,
    alignItems: "center",
    width: "100%",
    display: "flex",
  },
  headerCell: {
    fontSize: 13,
    fontWeight: "bold",
    color: Colors.darkGrey,
    textAlign: "left",
    paddingHorizontal: 10,
    flex: 1,
  },
  headerCellRightmost: {
    fontSize: 13,
    fontWeight: "bold",
    color: Colors.darkGrey,
    textAlign: "center",
    width: 40,
    borderRightWidth: 0,
    paddingHorizontal: 0,
  },
  dataCellRightmost: {
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 0,
    paddingHorizontal: 0,
  },
  dataRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: Colors.tableRowBorder,
    paddingVertical: 8,
    width: "100%",
    display: "flex",
  },
  dataCell: {
    fontSize: 13,
    color: Colors.tableCellText,
    textAlign: "left",
    paddingHorizontal: 10,
    flex: 1,
  },
  actionButton: {
    backgroundColor: Colors.mediumGrey,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
  },
  actionButtonText: {
    color: Colors.black,
    fontSize: 13,
  },
  bottomButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  newRequestButton: {
    backgroundColor: Colors.buttonPrimary,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  newRequestButtonText: {
    color: Colors.white,
    fontWeight: "bold",
    fontSize: 16,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    margin: 20,
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 35,
    alignItems: "center",
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "80%",
    maxWidth: 400,
  },
  modalText: {
    marginBottom: 25,
    textAlign: "center",
    fontSize: 16,
    color: Colors.darkGrey,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  modalButton: {
    borderRadius: 4,
    padding: 10,
    elevation: 2,
    flex: 1,
    marginHorizontal: 5,
  },
  buttonCancel: {
    backgroundColor: "#999",
  },
  buttonConfirm: {
    backgroundColor: Colors.buttonPrimary,
  },
  buttonTextStyle: {
    color: Colors.white,
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 16,
  },
  statusPill: {
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
    fontWeight: "bold",
    fontSize: 11,
    textAlign: "center",
  },
  pendingStatus: {
    backgroundColor: Colors.pendingStatus,
    color: Colors.textBorder,
  },
  deniedStatus: {
    backgroundColor: Colors.deniedStatus,
    color: Colors.textBorder,
  },
  approvedStatus: {
    backgroundColor: Colors.approvedStatus,
    color: Colors.textBorder,
  },
  unselectedStudentIndicator: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: Colors.tableBorder,
    borderRadius: 3,
    backgroundColor: Colors.white,
  },
  selectedStudentIndicator: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: Colors.buttonRed,
    borderRadius: 3,
    backgroundColor: Colors.buttonRed,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#222222",
  },
  baseContainer: {
    flex: 1,
    backgroundColor: Colors.background,
    justifyContent: "center",
    alignItems: "center",
  },
  baseLogo: {
    width: 50,
    height: 50,
    marginBottom: 40,
    resizeMode: "contain",
  },
  baseTitle: {
    fontSize: 28,
    fontWeight: "normal",
    marginBottom: 0,
    color: Colors.textBorder,
  },
  baseInput: {
    width: "80%",
    height: 50,
    backgroundColor: "transparent",
    borderRadius: 4,
    paddingHorizontal: 15,
    marginBottom: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: Colors.textBorder,
  },
  baseInputMedium: {
    width: "40%",
    height: 50,
    backgroundColor: "transparent",
    borderRadius: 4,
    paddingHorizontal: 15,
    marginBottom: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: Colors.textBorder,
  },
  baseInputSmall: {
    width: "20%",
    height: 50,
    backgroundColor: "transparent",
    borderRadius: 4,
    paddingHorizontal: 15,
    marginBottom: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: Colors.textBorder,
  },
  baseButtonRed: {
    width: "80%",
    height: 50,
    backgroundColor: Colors.buttonRed,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  baseButtonGreen: {
    width: "80%",
    height: 50,
    backgroundColor: Colors.buttonGreen,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  baseButtonTransparent: {
    width: "80%",
    height: 50,
    backgroundColor: "transparent",
    borderColor: "#222222",
    borderWidth: 1,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  baseButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: "normal",
  },
  horizontalLine: {
    width: "100%",
    borderBottomColor: Colors.buttonRed,
    borderBottomWidth: 4,
    marginVertical: 30,
  },
  pickerContainer: {
    fontSize: 16,
    borderRadius: 5,
    overflow: "hidden",
  },
  picker: {
    height: 63,
    width: 180,
    backgroundColor: Colors.mediumGrey,
  },
});

export default globalStyles;
